version: "3"
services:
  gcs:
    image: fsouza/fake-gcs-server
    ports:
      - 4443:4443
    volumes:
      - ./lecturia-public-storage:/data/${GOOGLE_CLOUD_STORAGE_PUBLIC_BUCKET_NAME}
    command:
      ["-scheme", "http", "-port", "4443", "-external-url", "http://gcs:4443"]
  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/${PROJECT_ID}/locations/asia-northeast1/queues/lecture-queue"
    ports:
      - "${TASKS_PORT:-8123}:8123"
    environment:
      APP_ENGINE_EMULATOR_HOST: http://localhost:8080
  lecturia:
    build:
      context: .
      dockerfile: Dockerfile
    image: lecturia:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - STORAGE_EMULATOR_HOST=http://gcs:4443
      - WORKER_URL=http://worker:8001
    env_file:
      - .env
    depends_on:
      - gcs
      - gcloud-tasks-emulator
  worker:
    image: lecturia:latest
    command: ["fastapi", "run", "src/lecturia/cloud_pipeline/workflow.py", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - STORAGE_EMULATOR_HOST=http://gcs:4443
    env_file:
      - .env
